
theme: jekyll-theme-cayman
title: Hardware Aware Efficient Training
description: Tentative workshop at NeurIPS 2023

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  Organisers: "/organisers"
  Keynotes: "/speakers"
  
 
markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true


